Update K1.yml

diff --git a/.github/workflows/K1.yml b/.github/workflows/K1.yml
--- a/.github/workflows/K1.yml
+++ b/.github/workflows/K1.yml
@@ -1,110 +1,87 @@
-# # # # # # # # # # #
-#  自动构建PSG1208
-#      
-# # # # # # # # # # #
+#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
 name: Padavan PSG1208
+
 on: 
   release:
     types: [published]
   push:
-#    branches: 
-#      - master
-
+    tags:
+    - 'v*'
+  #  branches: 
+  #    - master
 #  schedule:
-#    - cron: 0 19 * * *
+#    - cron: 0 8 * * 5
   watch:
     types: [started]
 
-env:
-  T_NAMES: "PSG1208"        # 设备名字数组
-  BASE_PATH: padavan                # 基础目录
-  PUBLIC_PATH: public               # 公共目录
-  VERSION_FILE: versions.inc        # 版本后缀
-  PUBLIC_SH: public.sh              # 公共命令
-  THEME_PATH: theme
-  UPLOAD_FIRMWARE: true             # 是否打包文件
-  CLONE_URL: https://github.com/chongshengB/rt-n56u.git    # padavan  地址
-  CLONE_BRANCH: master              # padavan 分支
-  WORK_PATH: /opt/rt-n56u           # 工作目录 一定要加 /
-  UPLOAD_COWTRANSFER: true
-  UPLOAD_WETRANSFER: true
 jobs:
   build:
     runs-on: ubuntu-18.04
-    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
+    if: github.event.repository.owner.id == github.event.sender.id
+
     steps:
-    - name: Checkout Master            # 1.导入主分支
+    - name: Checkout
       uses: actions/checkout@master
-    - name: Initialization Environment # 2.初始环境的设置
+    - name: Initialization environment
       env:
-        DEBIAN_FRONTEND: noninteractive  # 非交互模式
+        DEBIAN_FRONTEND: noninteractive
       run: |
         sudo apt-get update
         sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
         cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
         pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
-        sudo timedatectl set-timezone 'Asia/Shanghai'  # 设置时区
-    - name: Clone Code                 # 3.拷贝代码
+    - name: Clone source code
       run: |
-        git clone --depth=1 $CLONE_URL -b $CLONE_BRANCH $WORK_PATH
-    - name: Build Tool Chain           # 4.构建工具链
-      run: |
-        cd $WORK_PATH/toolchain-mipsel
+        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
+        cd /opt/rt-n56u/toolchain-mipsel
         sh dl_toolchain.sh
-        # mkdir -p toolchain-3.4.x
-        # wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
-        # tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
-        mkdir ${WORK_PATH}/images/
-    - name: Clear And Build            # 5.清理构建树并开始构建
+        mkdir -p /opt/images/
+    
+    - name: Build Firmware
+      env:
+        T_NAMES: "PSG1208"
       run: |
-        # 1.拷贝公共文件
-        cp -r $BASE_PATH/$PUBLIC_PATH  $WORK_PATH/
-        sudo chmod +x $WORK_PATH/$PUBLIC_PATH/$PUBLIC_SH
-        # 2. 循环替换自定义默认模板和构建，单个设备的 sh 拷贝 t_item 需要编译的固件名字
         for t_item in $T_NAMES;
         do
-        if [ ! -e $BASE_PATH/$t_item/$t_item.config ] ; then
-          echo "${BASE_PATH}/${t_item}/${t_item}.config 自定义模板文件未找到"
+        if [ -f padavan/shadowsocks.sh ] ; then
+          mv -f padavan/$t_item/shadowsocks.sh /opt/rt-n56u/trunk/user/shadowsocks/scripts/shadowsocks.sh
+        echo "shadowsocks SH文件拷贝成功"
         else
-          cp -f $BASE_PATH/$t_item/$t_item.config $WORK_PATH/trunk/configs/templates/$t_item.config
-          echo "${t_item} 修改模板完成"
-        fi
-        if [ ! -f $BASE_PATH/$t_item/$t_item.sh ] ; then
-          echo "${BASE_PATH}/${t_item}/${t_item}.sh 自定义SH文件未找到"
-        else
-          cp -f $BASE_PATH/$t_item/$t_item.sh  $WORK_PATH/
-          sudo chmod +x $WORK_PATH/$t_item.sh
-          echo "${t_item} 自定义SH文件拷贝成功"
-        fi
-        if [ ! -d $BASE_PATH/$t_item/$THEME_PATH ] ; then
-          echo "${BASE_PATH}/${t_item}/${THEME_PATH} 自定义主题文件夹未找到"
-        elif [! -d $WORK_PATH/$PUBLIC_PATH/$THEME_PATH ] ; then
-              cp -r $BASE_PATH/$t_item/$THEME_PATH  $WORK_PATH/$PUBLIC_PATH
-              echo "${THEME_PATH} 自定义主题文件夹拷贝成功"  
-           else
-               #删除public拷贝的主题
-              sudo rm -rf $WORK_PATH/$PUBLIC_PATH/$THEME_PATH
-              cp -r $BASE_PATH/$t_item/$THEME_PATH  $WORK_PATH/$PUBLIC_PATH
-              echo "${THEME_PATH} 自定义主题文件夹拷贝成功"  
-        fi
-        done
-        # 3. 执行sh程序
-        echo "执行 ${PUBLIC_SH} sh"
-        sudo $WORK_PATH/$PUBLIC_PATH/$PUBLIC_SH
-        if [ -e $WORK_PATH/$t_item.sh ] ; then
-          echo "执行自定义 ${t_item} sh"
-          sudo $WORK_PATH/$t_item.sh
-        fi
-    - name: Build Firmware             # 3.开始构建
-      env:
-        TNAME: PSG1218
-      run: |
-        cd /opt/rt-n56u/trunk
-        if [ ! -f configs/templates/$TNAME.config ] ; then
-        echo "configs/templates/$TNAME.config not found "
         exit 1
+        fi 
+        if [ -f padavan/PSG1218_hzn.config ] ; then
+        mv -f padavan/$t_item/$t_item.config /opt/rt-n56u/trunk/configs/templates/$t_item.config
+        echo "${t_item} config文件拷贝成功"
+        else
+        exit 2
+        fi 
+        if [ -f padavan/$t_item/defaults.h ] ; then
+          mv -f padavan/$t_item/defaults.h /opt/rt-n56u/trunk/user/shared/defaults.h
+          echo "${t_item} 配置文件拷贝成功"
+        else
+        exit 3
+        fi 
+        if [ ! -d padavan/$t_item/theme ] ; then
+          echo "padavan}/${t_item}/theme 自定义主题文件夹未找到"
+        elif [! -d $WORK_PATH/theme ] ; then
+              cp -r padavan/$t_item/theme  /opt/rt-n56u/
+              echo "theme 自定义主题文件夹拷贝成功"  
+           else
+              rm -rf $WORK_PATH/theme
+              cp -r padavan/$t_item/theme  /opt/rt-n56u/
+              sudo rm -rf /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/bootstrap
+              sudo rm -rf /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/images
+              cp -rf /opt/rt-n56u/theme/. /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed
+              echo "theme 复制主题文件结束"  
+        else
+        exit 4
         fi
-        cp -f configs/templates/$TNAME.config .config
+        cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$T_NAMES.config ] ; then
+        echo "configs/templates/$T_NAMES.config not found "
+        exit 5
+        fi
+        cp -f configs/templates/$T_NAMES.config .config
         sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
         ################################################################################################
         #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
@@ -155,27 +132,12 @@ jobs:
         #sed -i '/自定义项/d' .config
         #echo "自定义项=y" >> .config
         #########################################################################################
-        sudo ./clear_tree  
-        sudo ./build_firmware_modify $t_item          # $t_item  是循环的子对象
-        sudo mv -f images/*.trx ${WORK_PATH}/images/
-        done
-        echo "::set-env name=FILE_NAME::$T_NAMES-$(date "+%Y%m%d")"  # 包名
-        echo "::set-env name=IMAGES_PATH::${WORK_PATH}/images/"      # 打包目录
-    - name : Upload Packages           # 6. 打包文件并且上传到当前主分支
+        sudo ./clear_tree
+        sudo ./build_firmware_modify $TNAME 0
+        sudo mv -f images/*.trx /opt/images/
+    - name : Upload packages
       uses: actions/upload-artifact@master
-      if: env.UPLOAD_FIRMWARE == 'true' && success()   # 成功才执行
+      if: always()
       with:
-        name: Padavan-${{env.FILE_NAME}}
-        path: ${{ env.IMAGES_PATH }}
-    - name: Upload firmware to cowtransfer
-      if: env.UPLOAD_COWTRANSFER == 'true' && success()
-      run: |
-        curl -fsSL git.io/file-transfer | sh
-        ./transfer cow --block 2621440 -s -p 64 --no-progress ${IMAGES_PATH} 2>&1 | tee cowtransfer.log
-        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
-    - name: Upload firmware to WeTransfer
-      if: env.UPLOAD_WETRANSFER == 'true' && success()
-      run: |
-        curl -fsSL git.io/file-transfer | sh
-        ./transfer wet -s -p 16 --no-progress ${IMAGES_PATH} 2>&1 | tee wetransfer.log
-        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
+        name: Padavan-packages
+        path: /opt/images
